#!/bin/bash
# ============================================================
#  VAPT EXP 11 — WIRESHARK (HTTP vs HTTPS Credential Capture)
# ============================================================
echo "============================================================"
echo "  VAPT EXPERIMENT 11 : WIRESHARK"
echo "  Capturing credentials over HTTP (plain) vs HTTPS (encrypted)"
echo "============================================================"

# Install Wireshark if missing
if ! command -v wireshark &>/dev/null; then
    echo "[*] Installing Wireshark..."
    sudo apt update -qq
    sudo DEBIAN_FRONTEND=noninteractive apt install -y wireshark
    # Allow non-root capture
    sudo usermod -aG wireshark "$USER" 2>/dev/null
    echo "[!] You may need to log out and back in for group changes."
fi

echo ""
echo "============================================================"
echo "  PART A : HTTP (Unsecured — Credentials Visible)"
echo "============================================================"
echo ""
echo "  STEP 1 : Open Wireshark"
echo "           Run: wireshark  (or sudo wireshark)"
echo ""
echo "  STEP 2 : Start Capture"
echo "           Select your network interface (e.g., eth0)"
echo "           Click the blue shark fin icon to START capture"
echo ""
echo "  STEP 3 : Browse HTTP website"
echo "           Open browser → go to:"
echo "           http://testphp.vulnweb.com/login.php"
echo "           Enter fake credentials:"
echo "           Username: testuser"
echo "           Password: testpass123"
echo "           Click Login"
echo ""
echo "  STEP 4 : Stop Capture in Wireshark"
echo "           Click the red Stop button"
echo ""
echo "  STEP 5 : Filter for HTTP traffic"
echo "           In the filter bar type:  http"
echo "           Press Enter"
echo ""
echo "  STEP 6 : Find the POST request"
echo "           Look for packet with: POST /login.php"
echo "           Click on it → Expand 'HTML Form URL Encoded'"
echo "           You will see: username=testuser&password=testpass123"
echo "           *** CREDENTIALS VISIBLE IN PLAIN TEXT ***"
echo ""
echo "============================================================"
echo "  PART B : HTTPS (Secured — Credentials Encrypted)"
echo "============================================================"
echo ""
echo "  STEP 1 : Start a new Wireshark capture (same as above)"
echo ""
echo "  STEP 2 : Browse HTTPS website"
echo "           Open browser → go to:"
echo "           https://www.google.com (or any HTTPS login page)"
echo "           Enter fake credentials and submit"
echo ""
echo "  STEP 3 : Stop Capture"
echo ""
echo "  STEP 4 : Filter for TLS traffic"
echo "           In the filter bar type:  tls"
echo "           Press Enter"
echo ""
echo "  STEP 5 : Try to find credentials"
echo "           Click any TLS packet → Expand layers"
echo "           You will see: 'Encrypted Application Data'"
echo "           *** CREDENTIALS ARE ENCRYPTED — NOT READABLE ***"
echo ""
echo "============================================================"
echo "  COMPARISON TABLE:"
echo ""
echo "  Feature          | HTTP              | HTTPS"
echo "  ---------------  | ----------------  | ----------------"
echo "  Protocol         | HTTP/1.1          | TLS + HTTP"
echo "  Port             | 80                | 443"
echo "  Credentials      | PLAINTEXT visible | Encrypted"
echo "  Wireshark filter | http              | tls"
echo "  Risk level       | CRITICAL          | LOW (if TLS ok)"
echo "  Packet type      | POST form data    | App Data (opaque)"
echo ""
echo "============================================================"
echo "  KEY THINGS TO OBSERVE:"
echo "  1. HTTP POST shows username & password in clear text"
echo "  2. HTTPS shows only encrypted binary data"
echo "  3. TLS handshake packets visible but data not readable"
echo "  4. Certificate info visible in TLS Client Hello"
echo "============================================================"
echo "  SECURITY LESSON:"
echo "  NEVER send credentials over HTTP. Always use HTTPS."
echo "  DEFENSE: Enforce HTTPS with HSTS headers,"
echo "  redirect all HTTP → HTTPS, use TLS 1.2/1.3 only."
echo "============================================================"

# Launch Wireshark
echo ""
echo "  Launching Wireshark..."
wireshark &>/dev/null &
