#!/bin/bash
# ============================================================
#  VAPT EXP 8 — FTK Imager (Digital Forensics - Disk Imaging)
# ============================================================
echo "============================================================"
echo "  VAPT EXPERIMENT 8 : FTK IMAGER"
echo "  (Digital Forensics — Disk Imaging & Hash Verification)"
echo "============================================================"
echo ""
echo "  FTK Imager is a Windows GUI forensics tool."
echo "  Follow the step-by-step procedure below carefully."
echo ""
echo "------------------------------------------------------------"
echo "  STEP-BY-STEP PROCEDURE:"
echo "------------------------------------------------------------"
echo ""
echo "  STEP 1 : Launch FTK Imager"
echo "           Double-click FTK Imager on Desktop"
echo "           (Run as Administrator if prompted)"
echo ""
echo "  STEP 2 : Create Disk Image"
echo "           File → Create Disk Image"
echo "           Source Type: Select 'Image File'"
echo "           Click Next"
echo "           Browse and select the given evidence image file"
echo ""
echo "  STEP 3 : Select Image Format"
echo "           Choose: E01  ← RECOMMENDED (EnCase format)"
echo "           (E01 supports compression + hash verification)"
echo ""
echo "  STEP 4 : Set Destination"
echo "           Click 'Add' → Choose output folder"
echo "           Set image filename (e.g., evidence_copy)"
echo "           Tick: 'Verify images after they are created'"
echo "           Click Finish to start imaging"
echo ""
echo "  STEP 5 : Observe Acquisition Details"
echo "           - Image format (E01)"
echo "           - Compression level"
echo "           - Sector size"
echo "           - Total sectors"
echo "           - Acquisition time"
echo ""
echo "  STEP 6 : Observe Hash Values"
echo "           After imaging completes, FTK shows:"
echo "           - MD5 hash of source"
echo "           - MD5 hash of destination image"
echo "           BOTH MUST MATCH — proves integrity"
echo "           (Also shows SHA1 hash)"
echo ""
echo "  STEP 7 : Observe File Metadata"
echo "           File → Add Evidence Item → Image File"
echo "           Select your .E01 image"
echo "           Expand the tree in the left panel"
echo "           Click any file to see metadata:"
echo "           - File name, size"
echo "           - Created / Modified / Accessed timestamps"
echo "           - File path and owner"
echo "           - MD5 hash of individual file"
echo ""
echo "============================================================"
echo "  KEY THINGS TO OBSERVE:"
echo "  1. Source and destination MD5/SHA1 hashes match"
echo "  2. File timestamps (creation, modification, access)"
echo "  3. Deleted files visible in FTK tree"
echo "  4. File metadata (owner, path, size)"
echo "  5. Acquisition log / case details"
echo "============================================================"
echo "  PURPOSE:"
echo "  - Creates forensically sound copy of evidence"
echo "  - Hash verification ensures no tampering occurred"
echo "  - Metadata helps reconstruct timeline of events"
echo "  DEFENSE: Maintain chain of custody, write-blockers"
echo "  must be used when imaging live media."
echo "============================================================"
