#!/bin/bash
# ============================================================
#  VAPT EXP 9 — AUTOPSY (Digital Forensics Analysis)
# ============================================================
echo "============================================================"
echo "  VAPT EXPERIMENT 9 : AUTOPSY"
echo "  (Digital Forensics — Evidence Analysis)"
echo "============================================================"
echo ""
echo "  Autopsy is a GUI forensics platform."
echo "  Follow the step-by-step procedure below."
echo ""

# Install Autopsy if not present (Linux)
if ! command -v autopsy &>/dev/null; then
    echo "[*] Autopsy not found. Attempting install..."
    sudo apt update -qq && sudo apt install -y autopsy 2>/dev/null
fi

echo ""
echo "------------------------------------------------------------"
echo "  STEP-BY-STEP PROCEDURE:"
echo "------------------------------------------------------------"
echo ""
echo "  STEP 1 : Launch Autopsy"
echo "           Run as Administrator (right-click → Run as Admin)"
echo "           On Kali: sudo autopsy"
echo ""
echo "  STEP 2 : Create New Case"
echo "           Click 'New Case'"
echo "           Enter Case Name (e.g., VAPT_Lab_Case)"
echo "           Choose output directory"
echo "           Click Next → Finish"
echo ""
echo "  STEP 3 : Add Data Source"
echo "           Click 'Add Data Source'"
echo "           Select type: 'Disk Image or VM File'"
echo "           Browse and select the .E01 image file"
echo "           Click Next"
echo ""
echo "  STEP 4 : Configure Ingest Modules"
echo "           Enable ALL of these modules:"
echo "           ✔ File Type Identification"
echo "           ✔ Keyword Search"
echo "           ✔ Hash Lookup"
echo "           ✔ Web Artifacts"
echo "           ✔ Email Parser"
echo "           ✔ Recent Activity"
echo "           ✔ Timeline Analysis"
echo "           Click Finish — analysis begins automatically"
echo ""
echo "  STEP 5 : Observe Artifacts in Left Panel"
echo ""
echo "  [A] DELETED FILES:"
echo "      Left panel → 'Deleted Files'"
echo "      Observe: Filename, original path, timestamps"
echo "      Right-click → Extract File (to recover)"
echo ""
echo "  [B] WEB ARTIFACTS:"
echo "      Left panel → 'Results' → 'Extracted Content'"
echo "      → 'Web History' / 'Web Bookmarks' / 'Web Cookies'"
echo "      Observe: URLs visited, timestamps, browser used"
echo ""
echo "  [C] RECENT DOCUMENTS:"
echo "      Results → Recent Documents"
echo "      Observe: Recently opened files and their paths"
echo ""
echo "  [D] TIMELINE ANALYSIS:"
echo "      Tools → Timeline"
echo "      Observe: Visual timeline of all file activity"
echo "      Filter by date range to find suspicious activity"
echo ""
echo "  [E] GENERATE REPORT:"
echo "      Generate Report → HTML Report → Finish"
echo "      Report saved in case output folder"
echo "      Open index.html in browser to view full report"
echo ""
echo "============================================================"
echo "  KEY THINGS TO OBSERVE:"
echo "  1. Deleted files still recoverable from disk"
echo "  2. Browser history and cookies (user activity)"
echo "  3. Timeline showing exact timestamps of events"
echo "  4. Email artifacts (sent/received messages)"
echo "  5. Keyword hits for suspicious terms"
echo "============================================================"
echo "  FORENSIC VALUE:"
echo "  - Autopsy recovers evidence thought to be deleted"
echo "  - Timeline helps reconstruct incident sequence"
echo "  - Hash verification confirms file authenticity"
echo "  - Reports are court-admissible documentation"
echo "============================================================"
